<div class="page-header">
  <h1>Edit abonnementperiode</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[from]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[from]">From date</label>
		<input class="form-control" name="subscriptionperiods[from]" type="date" value="<?php e($data['subscriptionperiods']['from']); ?>" id="subscriptionperiods[from]" />
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[from]'])) e($errors['subscriptionperiods[from]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[name]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[name]">Name</label>
		<input class="form-control" name="subscriptionperiods[name]" type="text" value="<?php e($data['subscriptionperiods']['name']); ?>" id="subscriptionperiods[name]" />
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[name]'])) e($errors['subscriptionperiods[name]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[subscription_id]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[subscription_id]">Subscription</label>
		<select class="form-control" name="subscriptionperiods[subscription_id]" id="subscriptionperiods[subscription_id]">
			<option value=""<?php e(''==$data['subscriptionperiods']['subscription_id']?' selected="selected"':''); ?>></option>
			<?php foreach ($subscriptions as $key => $value): ?>
			<option value="<?php e($key); ?>"<?php e($key==$data['subscriptionperiods']['subscription_id']?' selected="selected"':''); ?>><?php e($value); ?></option>
			<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[subscription_id]'])) e($errors['subscriptionperiods[subscription_id]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[comment]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[comment]">Comment</label>
		<input class="form-control" name="subscriptionperiods[comment]" type="text" value="<?php e($data['subscriptionperiods']['comment']); ?>" id="subscriptionperiods[comment]" />
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[comment]'])) e($errors['subscriptionperiods[comment]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 