<h1>Subscription months</h1>
<table class="table">
  <thead>
    <tr>
      <th class="date">From</th>
      <th class="name">Name</th>
      <th>Invoice</th>
      <th>subscriptions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($data as $row): ?>
    <tr>
      <td class="date"><span><?php e($row['subscriptionperiods']['from']);?></span></td>
      <td class="name"><span><?php e($row['subscriptionperiods']['name']);?></span></td>
      <td><span><?php if(isset($row['subscriptionperiods']['invoice_id'])) { ?><a href="invoices/view/<?php e($row['subscriptionperiods']['invoice_id']);?>"><?php e($invoices[$row['subscriptionperiods']['invoice_id']]);?></a><?php } ?></span></td>
      <td><span><a href="subscriptions/view/<?php e($row['subscriptionperiods']['subscription_id']);?>"><?php e($subscriptions[$row['subscriptionperiods']['subscription_id']]);?></a></span></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<p><a class="btn-primary" href="subscriptionperiods/add">Add abonnementperiode</a></p>