<?php Buffer::set('title','Login'); ?>
<h1>Login</h1>
<p>Got an account? Log in to InvoiceLion below.</p>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
    <div class="form-group">
        <label class="control-label" for="username">Username</label>
        <input class="form-control" type="text" id="username" name="username" />
    </div>
    <div class="form-group">
        <label class="control-label" for="password">Password<a href="auth/forgotten">Forgotten?</a></label>
        <input class="form-control" id="password" type="password" name="password"/>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
    <?php Session::getCsrfInput(); ?>
</form>

<p><a href="auth/register">Register</a></p>