<?php Buffer::set('title','Register'); ?>
<h1>Register</h1>
<p>Create your own InvoiceLion account. Enter your credentials below.</p>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
    <div class="form-group">
        <label class="control-label" for="username">Username (enter your email address)</label>
        <input class="form-control" id="username" type="text" name="username" />
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
    <?php Session::getCsrfInput(); ?>
</form>
