<?php Buffer::set('title','Dashboard'); ?>
<h2>Home</h2>
<h1>Dashboard</h1>

<p>This page tells you what to focus on.</p>

<div style="clear: both;">
    <div class="card col50">  
        <?php if(!isset($invoicelines_no_invoices[0])) { ?>
            <div class="status">
                <strong>Invoice line tasks</strong>
                <div class="img"></div>
                All done!
            </div>
        <?php } ?>
        <?php if(isset($invoicelines_no_invoices[0])) { ?>
            <table>
                <tr>
                    <th class="name">Invoice lines without invoice</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($invoicelines_no_invoices as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoicelines/view/<?php e($row['invoicelines']['id']);?>';">
                        <td class="name"><span><?php e($row['invoicelines']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['invoicelines']['subtotal']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
    </div>
    <div class="card col50">  
        <?php if(!isset($erronous_subscriptions[0]) && !isset($periods_no_invoices[0])) { ?>
            <div class="status">
                <strong>Subscription tasks</strong>
                <div class="img"></div>
                All done!
            </div>
        <?php } ?>
        <?php if(isset($erronous_subscriptions[0])) { ?>
            <table>
                <tr>
                    <th class="name">Subscriptions with missing months</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($erronous_subscriptions as $row): ?>
                    <tr class="hover" onclick="window.location.href='subscriptions/view/<?php e($row['subscriptions']['id']);?>';">
                        <td class="name"><span><?php e($row['subscriptions']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['subscriptions']['fee']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
        <?php if(isset($periods_no_invoices[0])) { ?>
        <?php if(isset($erronous_subscriptions[0])) { ?><br /><?php } ?>
            <table>
                <tr>
                    <th class="name">Subscription months without invoice</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($periods_no_invoices as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoicelines/view/<?php e($row['subscriptionperiods']['invoiceline_id']);?>';">
                        <td class="name"><span><?php e($row['subscriptionperiods']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['subscriptions']['fee']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
    </div>
</div>








<div style="clear: both;">
    <div class="card col50">  
        <?php if(!isset($unsent_invoices[0]) && !isset($unsent_reminders[0]) && !isset($unsent_reminders2[0])) { ?>
            <div class="status">
                <strong>Invoice tasks</strong>
                <div class="img"></div>
                All done!
            </div>
        <?php } ?>
        <?php if(isset($unsent_invoices[0])) { ?>
            <table>
                <tr>
                    <th class="name">Unsent invoices</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($unsent_invoices as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoices/view/<?php e($row['invoices']['id']);?>';">
                        <td class="name"><span><?php e($row['invoices']['number']); ?> - <?php e($row['invoices']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['invoices']['subtotal']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
        <?php if(isset($unsent_reminders[0])) { ?>
        <?php if(isset($unsent_invoices[0])) { ?><br /><?php } ?>
            <table>
                <tr>
                    <th class="name">Unsent first reminders</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($unsent_reminders as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoices/view/<?php e($row['invoices']['id']);?>';">
                        <td class="name"><span><?php e($row['invoices']['number']); ?> - <?php e($row['invoices']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['invoices']['subtotal']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
        <?php if(isset($unsent_reminders2[0])) { ?>
            <br />
            <table>
                <tr>
                    <th class="name">Unsent second reminders</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($unsent_reminders2 as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoices/view/<?php e($row['invoices']['id']);?>';">
                        <td class="name"><span><?php e($row['invoices']['number']); ?> - <?php e($row['invoices']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['invoices']['subtotal']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
    </div>

    <div class="card col50">    
        <?php if(!isset($unpaid_invoices[0])) { ?>
            <div class="status">
                <strong>Unpaid invoices</strong>
                <div class="img"></div>
                All paid!
            </div>
        <?php } ?> 
        <?php if(isset($unpaid_invoices[0])) { ?>
            <table>
                <tr>
                    <th class="name">Unpaid invoices</th>
                    <th class="money"></th>
                </tr>
                <?php foreach ($unpaid_invoices as $row): ?>
                    <tr class="hover" onclick="window.location.href='invoices/view/<?php e($row['invoices']['id']);?>';">
                        <td class="name"><span><?php e($row['invoices']['number']); ?> - <?php e($row['invoices']['name']); ?></span></td>
                        <td class="money"><span><?php e($row['invoices']['subtotal']); ?></span></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php } ?>
    </div>
</div>