<div class="page-header">
  <h1>New abonnementtype</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['subscriptiontypes[name]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptiontypes[name]">Name</label>
		<input class="form-control" name="subscriptiontypes[name]" type="text" value="<?php e($data['subscriptiontypes']['name']); ?>" id="subscriptiontypes[name]" />
		<span class="help-block"><?php if (isset($errors['subscriptiontypes[name]'])) e($errors['subscriptiontypes[name]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['subscriptiontypes[comment]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptiontypes[comment]">Text</label>
		<input class="form-control" name="subscriptiontypes[comment]" type="text" value="<?php e($data['subscriptiontypes']['comment']); ?>" id="subscriptiontypes[comment]" />
		<span class="help-block"><?php if (isset($errors['subscriptiontypes[comment]'])) e($errors['subscriptiontypes[comment]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 