<div class="page-header">
	<h2><a href="/">Home</a> / <a href="invoicelines">Invoicelines</a></h2>
  	<h1><?php e($data['invoicelines']['name']); ?></h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div><?php e($error); ?></div></div><?php endif; ?>
<form method="post">

	<div class="form-group <?php e(isset($errors['invoicelines[customer_id]'])?'has-error':''); ?>">
		<label class="control-label" for="invoicelines[customer_id]">Customer</label>
		<select class="form-control" name="invoicelines[customer_id]" id="invoicelines[customer_id]">
			<option value=""<?php e(''==$data['invoicelines']['customer_id']?' selected="selected"':''); ?>></option>
			<?php foreach ($customers as $key => $value): ?>
			<option value="<?php e($key); ?>"<?php e($key==$data['invoicelines']['customer_id']?' selected="selected"':''); ?>><?php e($value); ?></option>
			<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['invoicelines[customer_id]'])) e($errors['invoicelines[customer_id]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['invoicelines[invoice_id]'])?'has-error':''); ?>">
		<label class="control-label" for="invoicelines[invoice_id]">Invoice</label>
		<select class="form-control" name="invoicelines[invoice_id]" id="invoicelines[invoice_id]">
			<option value=""<?php e(''==$data['invoicelines']['invoice_id']?' selected="selected"':''); ?>></option>
			<?php foreach ($invoices as $key => $value): ?>
			<option value="<?php e($key); ?>"<?php e($key==$data['invoicelines']['invoice_id']?' selected="selected"':''); ?>><?php e($value); ?></option>
			<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['invoicelines[invoice_id]'])) e($errors['invoicelines[invoice_id]']); ?></span>
	</div>

    <div class="form-group <?php e(isset($errors['invoicelines[name]'])?'has-error':''); ?>">
		<label class="control-label" for="invoicelines[name]">Name</label>
		<input class="form-control" name="invoicelines[name]" type="text" value="<?php e($data['invoicelines']['name']); ?>" id="invoicelines[name]" />
		<span class="help-block"><?php if (isset($errors['invoicelines[name]'])) e($errors['invoicelines[name]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['invoicelines[subtotal]'])?'has-error':''); ?>">
		<label class="control-label" for="invoicelines[subtotal]">Subtotal</label>
		<input class="form-control" name="invoicelines[subtotal]" type="number" step="0.01" value="<?php e($data['invoicelines']['subtotal']); ?>" id="invoicelines[subtotal]" />
		<span class="help-block"><?php if (isset($errors['invoicelines[subtotal]'])) e($errors['invoicelines[subtotal]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['invoicelines[vat_percentage]'])?'has-error':''); ?>">
		<label class="control-label" for="invoicelines[vat_percentage]">VAT percentage</label>
		<input class="form-control" name="invoicelines[vat_percentage]" type="number" step="0.01" value="<?php e($data['invoicelines']['vat_percentage']); ?>" id="invoicelines[vat_percentage]" />
		<span class="help-block"><?php if (isset($errors['invoicelines[vat_percentage]'])) e($errors['invoicelines[vat_percentage]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 